<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Suchak Biodata Export #{{ $export->id }}</title>
    <style>
        body {
            color: #111827;
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            margin: 0;
        }

        .page {
            padding: 28px;
        }

        .header {
            border-bottom: 3px solid #dc2626;
            margin-bottom: 22px;
            padding-bottom: 16px;
        }

        .brand {
            color: #dc2626;
            font-size: 22px;
            font-weight: 700;
        }

        .muted {
            color: #6b7280;
        }

        .grid {
            display: table;
            table-layout: fixed;
            width: 100%;
        }

        .col {
            display: table-cell;
            vertical-align: top;
        }

        .col-main {
            padding-right: 22px;
            width: 68%;
        }

        .col-side {
            width: 32%;
        }

        .section {
            border: 1px solid #e5e7eb;
            margin-bottom: 14px;
            padding: 12px;
        }

        .section h2 {
            font-size: 14px;
            margin: 0 0 9px;
        }

        .row {
            border-bottom: 1px solid #f3f4f6;
            padding: 5px 0;
        }

        .row:last-child {
            border-bottom: 0;
        }

        .label {
            color: #6b7280;
            display: inline-block;
            font-size: 10px;
            font-weight: 700;
            text-transform: uppercase;
            width: 42%;
        }

        .value {
            display: inline-block;
            width: 56%;
        }

        .qr-box {
            border: 1px solid #d1d5db;
            padding: 12px;
            text-align: center;
        }

        .qr-box img {
            height: 170px;
            width: 170px;
        }

        .safe-note {
            background: #fff7ed;
            border: 1px solid #fed7aa;
            color: #7c2d12;
            margin-top: 12px;
            padding: 10px;
        }

        .footer {
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 10px;
            margin-top: 22px;
            padding-top: 10px;
        }
    </style>
</head>
<body>
@php
    $suchakDisplayName = $suchakAccount->office_name ?: $suchakAccount->suchak_name;
    $locationText = collect([
        $candidateSummary['location']['city'] ?? null,
        $candidateSummary['location']['district'] ?? null,
    ])->filter()->implode(', ');
    $communityText = collect([
        $candidateSummary['community']['religion'] ?? null,
        $candidateSummary['community']['caste'] ?? null,
    ])->filter()->implode(' / ');
@endphp
<div class="page">
    <div class="header">
        <div class="brand">Suchak Branded Biodata</div>
        <div class="muted">Generated by {{ $suchakDisplayName ?: 'Verified Suchak' }} through Navri Mile Navryala</div>
        <div class="muted">Export #{{ $export->id }} · {{ $generatedAt->format('Y-m-d H:i') }}</div>
    </div>

    <div class="grid">
        <div class="col col-main">
            <div class="section">
                <h2>Masked Candidate Summary</h2>
                <div class="row">
                    <span class="label">Reference</span>
                    <span class="value">{{ $candidateSummary['candidate_reference'] ?? 'masked-candidate' }}</span>
                </div>
                <div class="row">
                    <span class="label">Gender</span>
                    <span class="value">{{ $candidateSummary['basic']['gender'] ?? 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Age range</span>
                    <span class="value">{{ $candidateSummary['basic']['age_range'] ?? 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Height range</span>
                    <span class="value">{{ $candidateSummary['basic']['height_range'] ?? 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Marital status</span>
                    <span class="value">{{ $candidateSummary['basic']['marital_status'] ?? 'Not available' }}</span>
                </div>
            </div>

            <div class="section">
                <h2>Education, Work, Community</h2>
                <div class="row">
                    <span class="label">Education</span>
                    <span class="value">{{ $candidateSummary['education']['highest'] ?? 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Occupation</span>
                    <span class="value">{{ $candidateSummary['occupation']['broad'] ?? 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Community</span>
                    <span class="value">{{ $communityText !== '' ? $communityText : 'Not available' }}</span>
                </div>
                <div class="row">
                    <span class="label">Broad location</span>
                    <span class="value">{{ $locationText !== '' ? $locationText : 'Not available' }}</span>
                </div>
            </div>

            <div class="section">
                <h2>Representation</h2>
                <div class="row">
                    <span class="label">Status</span>
                    <span class="value">{{ ucfirst((string) ($candidateSummary['representation']['status'] ?? 'unknown')) }}</span>
                </div>
                <div class="row">
                    <span class="label">Consent</span>
                    <span class="value">{{ ucfirst((string) ($candidateSummary['representation']['consent_status'] ?? 'unknown')) }}</span>
                </div>
                <div class="row">
                    <span class="label">QR expires</span>
                    <span class="value">{{ $qrToken->expires_at?->format('Y-m-d H:i') ?: 'Not configured' }}</span>
                </div>
            </div>
        </div>

        <div class="col col-side">
            <div class="qr-box">
                <img src="{{ $qrImageDataUri }}" alt="Secure QR code">
                <div class="muted">Scan for masked online preview</div>
                <div style="font-size: 9px; margin-top: 8px; word-break: break-all;">{{ $qrUrl }}</div>
            </div>

            <div class="safe-note">
                Direct contact details, exact address, private identity fields, and profile photos are intentionally hidden.
            </div>
        </div>
    </div>

    <div class="footer">
        This PDF is governed Suchak evidence. Access depends on active representation, valid consent, QR expiry, and revocation status.
    </div>
</div>
</body>
</html>
