<?php

namespace App\Services\Onboarding;

use App\Models\EducationDegree;
use App\Models\MatrimonyProfile;
use App\Models\MobileOnboardingDraft;
use App\Models\PartnerPreferenceMetadata;
use App\Models\User;
use App\Services\EducationService;
use App\Services\MutationService;
use App\Services\PartnerPreferenceSnapshotBuilder;
use App\Services\PartnerPreferenceSuggestionService;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;

class RegistrationPartnerPreferenceService
{
    public const SOURCE = 'auto_from_registration';

    public const GENERATED_FROM = 'onboarding';

    public function __construct(
        private readonly MobileOnboardingDraftService $draftService,
        private readonly MutationService $mutationService,
    ) {}

    /**
     * @return array{profile: MatrimonyProfile, draft: MobileOnboardingDraft|null}
     */
    public function requireProfileForUser(User $user): array
    {
        $draft = $this->draftService->getForUser($user);
        $profile = $draft?->matrimony_profile_id
            ? MatrimonyProfile::query()->where('user_id', $user->id)->whereKey($draft->matrimony_profile_id)->first()
            : null;

        $profile ??= $this->draftService->existingProfileForUser($user);
        if (! $profile instanceof MatrimonyProfile) {
            throw ValidationException::withMessages([
                'profile' => 'Create the matrimony profile before generating partner preferences.',
            ]);
        }

        return ['profile' => $profile, 'draft' => $draft];
    }

    /**
     * @return array<string, mixed>
     */
    public function preview(User $user): array
    {
        $context = $this->requireProfileForUser($user);
        $generated = $this->generate($context['profile'], $context['draft']);

        return [
            'success' => true,
            'profile_id' => (int) $context['profile']->id,
            'source' => self::SOURCE,
            'can_persist' => true,
            'missing_fields' => $generated['missing_fields'],
            'strictness' => $generated['strictness'],
            'preference_strictness' => $generated['preference_strictness'],
            'preferences' => $generated['preferences'],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function persist(User $user, bool $forceRegenerate = false): array
    {
        $context = $this->requireProfileForUser($user);
        $profile = $context['profile'];
        $metadata = $this->metadataFor($profile);
        $hasPreferences = $this->hasStoredPreferences((int) $profile->id);

        if ($hasPreferences && ! $this->metadataIsAutoGenerated($metadata)) {
            throw new HttpResponseException(response()->json([
                'success' => false,
                'message' => 'Existing manually edited preferences will not be overwritten.',
                'editable' => true,
            ], 409));
        }

        if ($hasPreferences && $this->metadataIsAutoGenerated($metadata) && ! $forceRegenerate) {
            throw new HttpResponseException(response()->json([
                'success' => false,
                'message' => 'Auto-generated preferences already exist. Use force_regenerate to rebuild them.',
                'editable' => true,
            ], 409));
        }

        $generated = $this->generate($profile, $context['draft']);
        $validatedRow = $this->validatedPreferenceRow($generated['preferences']);

        DB::transaction(function () use ($profile, $user, $validatedRow, $generated): void {
            $this->mutationService->applyManualSnapshot(
                $profile,
                ['preferences' => [$validatedRow]],
                (int) $user->id,
                'manual'
            );

            PartnerPreferenceMetadata::query()->updateOrCreate(
                ['matrimony_profile_id' => (int) $profile->id],
                [
                    'source' => self::SOURCE,
                    'strictness_json' => $generated['strictness'],
                    'generated_from' => self::GENERATED_FROM,
                    'generated_at' => now(),
                ]
            );
        });

        $metadata = $this->metadataFor($profile->fresh());

        return [
            'success' => true,
            'profile_id' => (int) $profile->id,
            'source' => self::SOURCE,
            'preferences' => $validatedRow,
            'metadata' => $this->metadataPayload($metadata),
            'preference_strictness' => $generated['preference_strictness'],
            'editable' => true,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function statusForUser(User $user): array
    {
        $profile = $this->draftService->existingProfileForUser($user);

        return $this->statusForProfile($profile);
    }

    /**
     * @return array<string, mixed>
     */
    public function statusForProfile(?MatrimonyProfile $profile): array
    {
        if (! $profile instanceof MatrimonyProfile) {
            return [
                'profile_id' => null,
                'has_auto_draft' => false,
                'source' => null,
                'generated_at' => null,
                'editable' => true,
            ];
        }

        $metadata = $this->metadataFor($profile);

        return [
            'profile_id' => (int) $profile->id,
            'has_auto_draft' => $this->metadataIsAutoGenerated($metadata),
            'source' => $metadata?->source,
            'generated_at' => optional($metadata?->generated_at)?->toISOString(),
            'editable' => true,
        ];
    }

    /**
     * @return array{preferences: array<string, mixed>, strictness: array<string, string>, preference_strictness: array<string, string>, missing_fields: array<int, string>}
     */
    private function generate(MatrimonyProfile $profile, ?MobileOnboardingDraft $draft): array
    {
        $profile->loadMissing(['gender', 'maritalStatus']);

        $preferences = PartnerPreferenceSuggestionService::suggestForProfile($profile);
        $strictness = [];
        $preferenceStrictness = [];
        $missing = [];

        if ($profile->date_of_birth === null) {
            $missing[] = 'date_of_birth';
        }
        if ($profile->height_cm === null || $profile->height_cm === '') {
            $missing[] = 'height_cm';
        }
        if ($profile->gender_id === null || $profile->gender_id === '') {
            $missing[] = 'gender_id';
        }

        $draftReligion = $this->draftStep($draft, 'religion_caste');
        $this->applyCommunityPreference(
            $preferences,
            $strictness,
            $preferenceStrictness,
            $draftReligion,
            'religion_strictness',
            'same_religion_expected',
            'preferred_religion_ids',
            'religion',
            $profile->religion_id ? [(int) $profile->religion_id] : []
        );
        $this->applyCommunityPreference(
            $preferences,
            $strictness,
            $preferenceStrictness,
            $draftReligion,
            'caste_strictness',
            'same_caste_expected',
            'preferred_caste_ids',
            'caste',
            $profile->caste_id ? [(int) $profile->caste_id] : []
        );

        $subCasteStrictness = $this->communityStrictnessEnum(
            $draftReligion,
            'sub_caste_strictness',
            'same_sub_caste_required',
            $profile->sub_caste_id !== null
        );
        $strictness['sub_caste'] = $subCasteStrictness;
        $preferenceStrictness['sub_caste'] = $this->mappedPreferenceStrictness($subCasteStrictness, $profile->sub_caste_id !== null);
        if ($profile->sub_caste_id === null || $profile->sub_caste_id === '') {
            $missing[] = 'sub_caste_id';
        }

        $educationDegree = $this->educationDegreeFromProfile($profile);
        if ($educationDegree instanceof EducationDegree) {
            $preferences['preferred_education_degree_ids'] = [(int) $educationDegree->id];
            $strictness['education'] = 'preferred';
            $preferenceStrictness['education'] = 'preferred';
        } else {
            $missing[] = 'education_degree';
            $strictness['education'] = 'open';
            $preferenceStrictness['education'] = 'open';
        }

        if (! empty($profile->occupation_master_id)) {
            $preferences['preferred_occupation_master_ids'] = [(int) $profile->occupation_master_id];
            $strictness['occupation'] = 'preferred';
            $preferenceStrictness['occupation'] = 'preferred';
        } else {
            $strictness['occupation'] = 'open';
            $preferenceStrictness['occupation'] = 'open';
        }

        $strictness['age'] = ($preferences['preferred_age_min'] ?? null) !== null || ($preferences['preferred_age_max'] ?? null) !== null ? 'preferred' : 'open';
        $strictness['height'] = ($preferences['preferred_height_min_cm'] ?? null) !== null || ($preferences['preferred_height_max_cm'] ?? null) !== null ? 'preferred' : 'open';
        $strictness['marital_status'] = ($preferences['preferred_marital_status_ids'] ?? []) !== [] ? 'preferred' : 'open';
        $strictness['location'] = ($preferences['preferred_district_ids'] ?? []) !== [] || ($preferences['preferred_taluka_ids'] ?? []) !== [] ? 'preferred' : 'open';
        $strictness['income'] = ($preferences['preferred_income_min'] ?? null) !== null || ($preferences['preferred_income_max'] ?? null) !== null ? 'preferred' : 'open';
        $strictness['diet'] = ($preferences['preferred_diet_ids'] ?? []) !== [] ? 'preferred' : 'open';
        $strictness['gender'] = 'open';
        foreach (['age', 'height', 'marital_status', 'location', 'income', 'diet', 'gender'] as $key) {
            $preferenceStrictness[$key] = $strictness[$key];
        }

        unset($preferences['preferred_location_suggestions'], $preferences['preference_preset']);

        return [
            'preferences' => $preferences,
            'strictness' => $strictness,
            'preference_strictness' => $preferenceStrictness,
            'missing_fields' => array_values(array_unique($missing)),
        ];
    }

    private function educationDegreeFromProfile(MatrimonyProfile $profile): ?EducationDegree
    {
        $highest = trim((string) ($profile->highest_education ?? ''));
        if ($highest === '') {
            return null;
        }

        return app(EducationService::class)->findDegreeMatch($highest);
    }

    /**
     * @param  array<string, mixed>  $preferences
     * @param  array<string, string>  $strictness
     * @param  array<string, mixed>  $draftData
     * @param  array<int, int>  $profileIds
     */
    private function applyCommunityPreference(
        array &$preferences,
        array &$strictness,
        array &$preferenceStrictness,
        array $draftData,
        string $enumKey,
        string $toggleKey,
        string $preferenceKey,
        string $strictnessKey,
        array $profileIds
    ): void {
        $enum = $this->communityStrictnessEnum($draftData, $enumKey, $toggleKey, $profileIds !== []);
        $strictness[$strictnessKey] = $enum;
        $preferenceStrictness[$strictnessKey] = $this->mappedPreferenceStrictness($enum, $profileIds !== []);

        if ($enum === 'open') {
            $preferences[$preferenceKey] = [];

            return;
        }

        $preferences[$preferenceKey] = $profileIds;
    }

    private function communityStrictnessEnum(array $draftData, string $enumKey, string $legacyToggleKey, bool $hasValue): string
    {
        if (array_key_exists($enumKey, $draftData)) {
            return $this->normalizeStrictnessEnum($draftData[$enumKey]) ?? ($hasValue ? 'preferred' : 'open');
        }

        if (array_key_exists($legacyToggleKey, $draftData)) {
            return (bool) $draftData[$legacyToggleKey] ? 'required' : 'open';
        }

        return $hasValue ? 'preferred' : 'open';
    }

    private function normalizeStrictnessEnum(mixed $value): ?string
    {
        if ($value === null || $value === '') {
            return null;
        }

        return match (str_replace('-', '_', strtolower(trim((string) $value)))) {
            'required', 'must_match' => 'required',
            'preferred' => 'preferred',
            'open' => 'open',
            default => null,
        };
    }

    private function mappedPreferenceStrictness(string $strictness, bool $hasValue): string
    {
        if ($strictness === 'required') {
            return $hasValue ? 'must_match' : 'open';
        }

        return $strictness;
    }

    /**
     * @return array<string, mixed>
     */
    private function draftStep(?MobileOnboardingDraft $draft, string $step): array
    {
        $data = $draft?->draft_data;
        $stepData = is_array($data) ? ($data[$step] ?? []) : [];

        return is_array($stepData) ? $stepData : [];
    }

    /**
     * @param  array<string, mixed>  $preferences
     * @return array<string, mixed>
     */
    private function validatedPreferenceRow(array $preferences): array
    {
        $request = Request::create('/api/v1/onboarding/preferences/auto-draft', 'POST', $preferences);

        return PartnerPreferenceSnapshotBuilder::validateAndBuildRow($request);
    }

    private function metadataFor(MatrimonyProfile $profile): ?PartnerPreferenceMetadata
    {
        if (! Schema::hasTable('partner_preference_metadata')) {
            return null;
        }

        return PartnerPreferenceMetadata::query()
            ->where('matrimony_profile_id', (int) $profile->id)
            ->first();
    }

    private function metadataIsAutoGenerated(?PartnerPreferenceMetadata $metadata): bool
    {
        return $metadata instanceof PartnerPreferenceMetadata && $metadata->source === self::SOURCE;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function metadataPayload(?PartnerPreferenceMetadata $metadata): ?array
    {
        if (! $metadata instanceof PartnerPreferenceMetadata) {
            return null;
        }

        return [
            'source' => $metadata->source,
            'generated_from' => $metadata->generated_from,
            'generated_at' => optional($metadata->generated_at)?->toISOString(),
            'strictness' => $metadata->strictness_json ?? [],
        ];
    }

    private function hasStoredPreferences(int $profileId): bool
    {
        if (Schema::hasTable('profile_preference_criteria')
            && DB::table('profile_preference_criteria')->where('profile_id', $profileId)->exists()) {
            return true;
        }

        foreach ([
            'profile_preferred_religions',
            'profile_preferred_castes',
            'profile_preferred_countries',
            'profile_preferred_states',
            'profile_preferred_districts',
            'profile_preferred_talukas',
            'profile_preferred_education_degrees',
            'profile_preferred_occupation_master',
            'profile_preferred_diets',
            'profile_preferred_marital_statuses',
        ] as $table) {
            if (Schema::hasTable($table) && DB::table($table)->where('profile_id', $profileId)->exists()) {
                return true;
            }
        }

        return false;
    }
}
