{{-- Phase-5 SSOT: Full edit — all sections in one form (used when section=full, e.g. from Edit Profile / matrimony.profile.edit). --}}
@include('matrimony.profile.wizard.sections.basic_info')
@include('matrimony.profile.wizard.sections.personal_family')
@include('matrimony.profile.wizard.sections.siblings')
@include('matrimony.profile.wizard.sections.relatives')
@include('matrimony.profile.wizard.sections.alliance')
@include('matrimony.profile.wizard.sections.location')
@include('matrimony.profile.wizard.sections.property')
@include('matrimony.profile.wizard.sections.horoscope')
@include('matrimony.profile.wizard.sections.legal')
@include('matrimony.profile.wizard.sections.contacts')
@include('matrimony.profile.wizard.sections.about_preferences')
