"""
Single SSOT for matrimony_profile governance logical fields (Phase-6A).

Logical keys MUST match SnapshotGeneratorService::captureDb() keys and snapshot `db` payload.
API aliases are the keys emitted by MatrimonyProfileApiController JSON (parity layer).
"""

from __future__ import annotations

from typing import Any

# Deterministic ordering: scalars first (sorted by field), then repeaters (sorted).
_CANONICAL_SCALAR_ENTRIES: list[dict[str, Any]] = [
    {
        "field": "annual_income",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → annual_income",
            "db": "matrimony_profiles.annual_income",
            "api": "profile.annual_income",
            "public_profile": "rendered.fields.*.annual_income",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["annual_income"],
        "db_column": "annual_income",
    },
    {
        "field": "blood_group",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → blood_group_id",
            "db": "matrimony_profiles.blood_group_id",
            "api": "profile.blood_group_id",
            "public_profile": "rendered.fields.*.blood_group",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["blood_group", "blood_group_id"],
        "db_column": "blood_group_id",
    },
    {
        "field": "caste",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → caste_id",
            "db": "matrimony_profiles.caste_id",
            "api": "profile.caste_id",
            "public_profile": "rendered.fields.*.caste",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["caste", "caste_id"],
        "db_column": "caste_id",
    },
    {
        "field": "city",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → location_id",
            "db": "matrimony_profiles.location_id",
            "api": "profile.location_id",
            "public_profile": "rendered.fields.*.city",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["city", "city_id", "location_id"],
        "db_column": "location_id",
    },
    {
        "field": "complexion",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → complexion_id",
            "db": "matrimony_profiles.complexion_id",
            "api": "profile.complexion_id",
            "public_profile": "rendered.fields.*.complexion",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["complexion", "complexion_id"],
        "db_column": "complexion_id",
    },
    {
        "field": "date_of_birth",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → date_of_birth",
            "db": "matrimony_profiles.date_of_birth",
            "api": "profile.date_of_birth",
            "public_profile": "rendered.fields.*.date_of_birth",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["date_of_birth"],
        "db_column": "date_of_birth",
    },
    {
        "field": "education",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → highest_education",
            "db": "matrimony_profiles.highest_education",
            "api": "profile.highest_education",
            "public_profile": "rendered.fields.*.education",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["education", "highest_education", "qualification"],
        "db_column": "highest_education",
    },
    {
        "field": "family_type",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → family_type_id",
            "db": "matrimony_profiles.family_type_id",
            "api": "profile.family_type_id",
            "public_profile": "rendered.fields.*.family_type",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["family_type", "family_type_id"],
        "db_column": "family_type_id",
    },
    {
        "field": "full_name",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → full_name",
            "db": "matrimony_profiles.full_name",
            "api": "profile.full_name",
            "public_profile": "rendered.fields.*.full_name",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["full_name"],
        "db_column": "full_name",
    },
    {
        "field": "gender",
        "category": "scalar",
        "source_paths": {
            "wizard": "users.gender / profile gender_id",
            "db": "matrimony_profiles.gender_id (+ users.gender)",
            "api": "profile.gender",
            "public_profile": "rendered.fields.*.gender",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["gender", "gender_id"],
        "db_column": "gender_id",
    },
    {
        "field": "height_cm",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → height_cm",
            "db": "matrimony_profiles.height_cm",
            "api": "profile.height_cm",
            "public_profile": "rendered.fields.*.height_cm",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["height_cm", "height"],
        "db_column": "height_cm",
    },
    {
        "field": "income_range",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → income_range_id",
            "db": "matrimony_profiles.income_range_id",
            "api": "profile.income_range_id",
            "public_profile": "rendered.fields.*.income_range",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["income_range", "income_range_id"],
        "db_column": "income_range_id",
    },
    {
        "field": "mangal_dosh",
        "category": "scalar",
        "source_paths": {
            "wizard": "horoscope → mangal_dosh_type_id",
            "db": "profile_horoscope.mangal_dosh_type_id",
            "api": "profile.mangal_dosh_type_id",
            "public_profile": "rendered.fields.*.mangal_dosh",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["mangal_dosh", "mangal_dosh_type_id", "mangal_status_id"],
        "db_column": "horoscope.mangal_dosh_type_id",
    },
    {
        "field": "marital_status",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → marital_status_id",
            "db": "matrimony_profiles.marital_status_id",
            "api": "profile.marital_status_id",
            "public_profile": "rendered.fields.*.marital_status",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["marital_status", "marital_status_id"],
        "db_column": "marital_status_id",
    },
    {
        "field": "mother_tongue",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → mother_tongue_id",
            "db": "matrimony_profiles.mother_tongue_id",
            "api": "profile.mother_tongue_id",
            "public_profile": "rendered.fields.*.mother_tongue",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["mother_tongue", "mother_tongue_id"],
        "db_column": "mother_tongue_id",
    },
    {
        "field": "nakshatra",
        "category": "scalar",
        "source_paths": {
            "wizard": "horoscope → nakshatra_id",
            "db": "profile_horoscope.nakshatra_id",
            "api": "profile.nakshatra_id",
            "public_profile": "rendered.fields.*.nakshatra",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["nakshatra", "nakshatra_id"],
        "db_column": "horoscope.nakshatra_id",
    },
    {
        "field": "occupation",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → occupation_title",
            "db": "matrimony_profiles.occupation_title",
            "api": "profile.occupation_title",
            "public_profile": "rendered.fields.*.occupation",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["occupation", "occupation_title"],
        "db_column": "occupation_title",
    },
    {
        "field": "partner_preferences",
        "category": "nested",
        "source_paths": {
            "wizard": "about-preferences → profile_preference_criteria",
            "db": "profile_preference_criteria.*",
            "api": "profile.partner_preferences",
            "public_profile": "rendered.fields.*.partner_preferences",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": False,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["partner_preferences"],
        "db_column": "profile_preference_criteria",
    },
    {
        "field": "professions",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → profession_id",
            "db": "matrimony_profiles.profession_id",
            "api": "profile.profession_id",
            "public_profile": "rendered.fields.*.professions",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["professions", "profession", "profession_id"],
        "db_column": "profession_id",
    },
    {
        "field": "rashi",
        "category": "scalar",
        "source_paths": {
            "wizard": "horoscope → rashi_id",
            "db": "profile_horoscope.rashi_id",
            "api": "profile.rashi_id",
            "public_profile": "rendered.fields.*.rashi",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["rashi", "rashi_id"],
        "db_column": "horoscope.rashi_id",
    },
    {
        "field": "religion",
        "category": "scalar",
        "source_paths": {
            "wizard": "matrimony/profile/wizard → religion_id",
            "db": "matrimony_profiles.religion_id",
            "api": "profile.religion_id",
            "public_profile": "rendered.fields.*.religion",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["religion", "religion_id"],
        "db_column": "religion_id",
    },
    {
        "field": "state",
        "category": "scalar",
        "source_paths": {
            "wizard": "residence hierarchy → state",
            "db": "matrimony_profiles / addresses.state_id",
            "api": "profile.state_id",
            "public_profile": "rendered.fields.*.state",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": True,
        "repeater": False,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "api_keys": ["state", "state_id"],
        "db_column": "state_id",
    },
]

_REPEATER_ENTRIES: list[dict[str, Any]] = [
    {
        "field": "career_history",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.career_history[]",
            "db": "profile_career",
            "api": "profile.career_history (when exposed)",
            "public_profile": "repeaters.career_history[].* in rendered flat",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": [
            "designation",
            "company",
            "location",
            "city_id",
            "start_year",
            "end_year",
            "is_current",
        ],
    },
    {
        "field": "children",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.children[]",
            "db": "profile_children",
            "api": "profile.children (when exposed)",
            "public_profile": "repeaters.children[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": ["child_name", "gender", "age", "child_living_with_id"],
    },
    {
        "field": "contacts",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.contacts[]",
            "db": "profile_contacts",
            "api": "profile.contacts (when exposed)",
            "public_profile": "repeaters.contacts[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": [
            "contact_relation_id",
            "phone_number",
            "is_primary",
            "verified_status",
        ],
    },
    {
        "field": "education_history",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.education_history[]",
            "db": "profile_education",
            "api": "profile.education_history (when exposed)",
            "public_profile": "repeaters.education_history[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": ["degree", "specialization", "university", "year_completed"],
    },
    {
        "field": "property_assets",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.property_assets[]",
            "db": "profile_property_assets",
            "api": "profile.property_assets (when exposed)",
            "public_profile": "repeaters.property_assets[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": ["asset_type_id", "ownership_type_id", "location", "notes"],
    },
    {
        "field": "relatives",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.relatives[]",
            "db": "profile_relatives",
            "api": "profile.relatives (when exposed)",
            "public_profile": "repeaters.relatives[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": [
            "relation_type",
            "name",
            "occupation",
            "occupation_master_id",
            "occupation_custom_id",
            "city_id",
            "state_id",
            "contact_number",
            "notes",
            "is_primary_contact",
        ],
    },
    {
        "field": "siblings",
        "category": "repeater",
        "source_paths": {
            "wizard": "repeaters.siblings[]",
            "db": "profile_siblings",
            "api": "profile.siblings (when exposed)",
            "public_profile": "repeaters.siblings[].*",
        },
        "governed": True,
        "comparison_supported": True,
        "snapshot_supported": True,
        "api_supported": False,
        "repeater": True,
        "normalization_supported": True,
        "lineage_supported": True,
        "status": "active",
        "repeater_row_fields": [
            "relation_type",
            "name",
            "gender",
            "marital_status",
            "occupation",
            "occupation_master_id",
            "occupation_custom_id",
            "city_id",
            "contact_number",
            "notes",
        ],
    },
]


def canonical_entries_for_export() -> list[dict[str, Any]]:
    """Return public registry rows (no internal api_keys/db_column in JSON if user schema forbids — keep for tooling)."""
    scalars = sorted(_CANONICAL_SCALAR_ENTRIES, key=lambda r: str(r["field"]))
    reps = sorted(_REPEATER_ENTRIES, key=lambda r: str(r["field"]))
    merged: list[dict[str, Any]] = []
    for row in scalars + reps:
        pub = {k: v for k, v in row.items() if k not in ("api_keys", "db_column")}
        merged.append(pub)
    return merged


def api_alias_map() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for row in _CANONICAL_SCALAR_ENTRIES:
        field = str(row["field"])
        keys = [field] + [str(x) for x in (row.get("api_keys") or []) if str(x) != field]
        seen: set[str] = set()
        uniq = []
        for k in keys:
            if k not in seen:
                seen.add(k)
                uniq.append(k)
        out[field] = uniq
    out["partner_preferences"] = ["partner_preferences"]
    return out
